<?php
DEFINE('DATABASE_CHARSET', 'utf8');
DEFINE('DATABASE_USER', 'root');
DEFINE('DATABASE_PASSWORD', '123456');
DEFINE('DATABASE_NAME', 'mbodak_camagru');
DEFINE('DATABASE_HOST', 'localhost');
DEFINE('DATABASE_PORT', '3306');
DEFINE('DATABASE_CONNECTION_STRING', 'mysql:host='.DATABASE_HOST.';port='.DATABASE_PORT.';dbname='.DATABASE_NAME.';charset='.DATABASE_CHARSET);
DEFINE('DATABASE_OPT', array(
    PDO::ATTR_ERRMODE            => PDO::ERRMODE_EXCEPTION,
    PDO::ATTR_DEFAULT_FETCH_MODE => PDO::FETCH_ASSOC,
    PDO::ATTR_EMULATE_PREPARES   => TRUE
));

DEFINE('IMAGE_DIRECTORY', '../images/');
DEFINE('AVATAR_DIRECTORY', IMAGE_DIRECTORY.'ava/');
